model_name: null

TRAIN:
  train_dir: null
  additional_train_dirs: null

  model_dir: null
  save_freq: null

  finetune_layer: null

  # set the lr schedule
  lr_schedule: "OneCycleLR"
  schedule_params:
    max_lr: 0.003
    epochs: null
    steps_per_epoch: -1
    pct_start: 0.3

  # setup the optimizer
  amp: True  # automatic mixed precision
  optimizer: "AdamW"
  optimizer_params:
    weight_decay: 0.1

  # performance metrics
  print_freq: 50
  metrics:
      - { metric: "IoU", name: "semantic_iou", labels: null, output_key: "sem_logits",  target_key: "sem"}

  # dataset parameters
  batch_size: 16
  workers: 4

  augmentations:
    - { aug: "RandomScale", scale_limit: [ -0.9, 1 ]}
    - { aug: "PadIfNeeded", min_height: null, min_width: null, border_mode: 0 }
    - { aug: "RandomCrop", height: null, width: null}
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.3, contrast_limit: 0.3 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }

EVAL:
  eval_dir: null
  epochs_per_eval: null

  # parameters needed for eval_metrics
  metrics:
      - { metric: "IoU", name: "semantic_iou", labels: null, output_key: "sem_logits",  target_key: "sem"}
      - { metric: "PQ", name: "pq", labels: null, label_divisor: 1000, output_key: "pan_seg",  target_key: "pan_seg"}
      - { metric: "F1", name: "f1_50", labels: null, label_divisor: 1000, iou_thr: 0.5, output_key: "pan_seg",  target_key: "pan_seg"}
